### ISSUE TITLE
TYPO3 Version contraint wrong?

### ISSUE THREAD

**Issue by bzgaLindner** [WSBusch/interamt_connect#1]
Hi, composer.json restricts TYPO3 to maximum version 11.5.99 whereas ext_emconf.php says 12.4.99. 

Could you please change composer.json, so that we can use this Extension with TYPO3 12.4.x?

Thank you!

(btw: are you shure that PHP 8.2 cannot be used here?)

**Comment by WSBusch** [comment]
Hi and thanks for your message.

The version constraint in the composer.json is adjusted, so now the installation under 12.4 works as well.
I have successfully tested the extension under PHP 8.2 and also included this version in the composer.json.
