### ISSUE TITLE
Cannot get interamt entries in TYPO3 11.5 or 12.4

### ISSUE THREAD

**Issue by bzgaLindner** [WSBusch/interamt_connect#2]
I try to use EXT:interamt_connect on TYPO3 v 11.5. and 12.4, but I do not get any entries with any partner ID. 

I used scheduler task without success. 

Setup is behind a proxy, which is set within LocalConfiguration.php

Did I miss anything? Can you give me a partner ID that works in your setup?

Thank you!

**Comment by bzgaLindner** [comment]
Works when setting proxy by
`CURLOPT_PROXY          => 'http://myproxyurl:myproxyport',`
in ConnectorService.php, lines 31 and 124.

**Comment by WSBusch** [comment]
Thank you for your information. I added an option die set up proxy information to the extension configuration.

**Comment by bzgaLindner** [comment]
Hi, I still cannot get any entries with any partner ID.

Reverting to my old settings (see above) did not help. Did the Interamt API change? There were some maintenance works last weeks.

Thx!

**Comment by WSBusch** [comment]
I am not aware of any changes to the API. Checks on my test instances (tested with several Interamt partner IDs) also run without any problems.
Is it possible for you to give me your partner ID (office@busch-oliver.de)? I can then test to see whether it is running under "normal" circumstances and whether there may still be a proxy problem that needs to be checked.

**Comment by bzgaLindner** [comment]
Test with latest release works as expected. Thanks a lot!
